version: '3.8'
services:
  postgres:
    container_name: energija_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: energija_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"

  pgadmin:
    container_name: energija_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
